FROM jenkinsci/blueocean:latest

RUN /usr/local/bin/install-plugins.sh git matrix-auth workflow-aggregator docker-workflow blueocean credentials-binding

ENV JENKINS_USER admin
ENV JENKINS_PASS admin

# Skip initial setup
ENV JAVA_OPTS "-Djenkins.install.runSetupWizard=false -Djenkins.CLI.disabled=true"

COPY config/executors.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY config/default-user.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY config/configure-jnlp-agent-protocols.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY config/configure-csrf-protection.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY config/security-disable-agent-master.groovy /usr/share/jenkins/ref/init.groovy.d/


VOLUME /var/jenkins_home
